### ISSUE TITLE
Code explaination?

### ISSUE THREAD

**Issue by toastmod** [planaria/vv#2]
Hi there, I'm trying to learn formant shifting and found your project, can you explain what's going on in this for-loop?
https://github.com/planaria/vv/blob/master/vv/src/processor.hpp#L67

**Comment by planaria** [comment]
Hello.
As I recall, in this line I calculated the power spectrum to compute the autocorrelation function.
The autocorrelation function can be computed by inverse Fourier transform of the power spectrum.

**Comment by toastmod** [comment]
Hey, I would what the purpose is of the following line. Does this have to do with KissFFT using 2pi as it's maximum in frequency domain?

**Comment by planaria** [comment]
Which line is it about?

**Comment by toastmod** [comment]
https://github.com/planaria/vv/blob/master/vv/src/processor.hpp#L55

Ah sorry I forgot to paste it lol

**Comment by planaria** [comment]
That line computes the window function.

**Comment by toastmod** [comment]
Hello again, I'm also wondering about the modifications you made to KissFFT.
I rewrote your code as a fork [here](http://github.com/toastmod/vv-rs) and used the [rustfft](https://github.com/ejmahler/RustFFT) library but I'm getting very different results from the FFT calculations. Are you able to explain why?
